/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bbi_linuxjoy_NoJoy */

#ifndef _Included_org_bbi_linuxjoy_NoJoy
#define _Included_org_bbi_linuxjoy_NoJoy
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bbi_linuxjoy_NoJoy_MAX_BUTTONS
#define org_bbi_linuxjoy_NoJoy_MAX_BUTTONS 64L
#undef org_bbi_linuxjoy_NoJoy_MAX_AXES
#define org_bbi_linuxjoy_NoJoy_MAX_AXES 64L
/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    nativePoll
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bbi_linuxjoy_NoJoy_nativePoll
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    openNativeDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_bbi_linuxjoy_NoJoy_openNativeDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    isNativeDeviceOpen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_bbi_linuxjoy_NoJoy_isNativeDeviceOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    enumerate
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_bbi_linuxjoy_NoJoy_enumerate
  (JNIEnv *, jclass);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    closeNativeDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bbi_linuxjoy_NoJoy_closeNativeDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    setNativeProperty
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_bbi_linuxjoy_NoJoy_setNativeProperty
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_bbi_linuxjoy_NoJoy
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_bbi_linuxjoy_NoJoy_getVersionString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
